let areaList = [
  'Abilene, TX MSA',
  'Akron, OH MSA',
  'Albany-Lebanon, OR MSA',
  'Albany-Schenectady-Troy, NY MSA',
  'Albany, GA MSA',
  'Albuquerque, NM MSA',
  'Alexandria, LA MSA',
  'Allentown-Bethlehem-Easton, PA-NJ MSA',
  'Altoona, PA MSA',
  'Amarillo, TX MSA',
  'Ames, IA MSA',
  'Anchorage, AK MSA',
  'Ann Arbor, MI MSA',
  'Anniston-Oxford, AL MSA',
  'Appleton, WI MSA',
  'Asheville, NC MSA',
  'Athens-Clarke County, GA MSA',
  'Atlanta-Sandy Springs-Alpharetta, GA MSA',
  'Atlantic City-Hammonton, NJ MSA',
  'Auburn-Opelika, AL MSA',
  'Augusta-Richmond County, GA-SC MSA',
  'Austin-Round Rock-Georgetown, TX MSA',
  'Bakersfield, CA MSA',
  'Baltimore-Columbia-Towson, MD MSA',
  'Bangor, ME MSA',
  'Barnstable Town, MA MSA',
  'Baton Rouge, LA MSA',
  'Battle Creek, MI MSA',
  'Bay City, MI MSA',
  'Beaumont-Port Arthur, TX MSA',
  'Beckley, WV MSA',
  'Bellingham, WA MSA',
  'Bend, OR MSA',
  'Billings, MT MSA',
  'Binghamton, NY MSA',
  'Birmingham-Hoover, AL MSA',
  'Bismarck, ND MSA',
  'Blacksburg-Christiansburg, VA MSA',
  'Bloomington, IL MSA',
  'Bloomington, IN MSA',
  'Bloomsburg-Berwick, PA MSA',
  'Boise City, ID MSA',
  'Boston-Cambridge-Newton, MA-NH MSA',
  'Boulder, CO MSA',
  'Bowling Green, KY MSA',
  'Bremerton-Silverdale-Port Orchard, WA MSA',
  'Bridgeport-Stamford-Norwalk, CT MSA',
  'Brownsville-Harlingen, TX MSA',
  'Brunswick, GA MSA',
  'Buffalo-Niagara Falls, NY MSA',
  'Burlington-South Burlington, VT MSA',
  'Burlington, NC MSA',
  'California-Lexington Park, MD MSA',
  'Canton-Massillon, OH MSA',
  'Cape Coral-Fort Myers, FL MSA',
  'Cape Girardeau, MO-IL MSA',
  'Carbondale-Marion, IL MSA',
  'Carson City, NV MSA',
  'Casper, WY MSA',
  'Cedar Rapids, IA MSA',
  'Chambersburg-Waynesboro, PA MSA',
  'Champaign-Urbana, IL MSA',
  'Charleston-North Charleston, SC MSA',
  'Charleston, WV MSA',
  'Charlotte-Concord-Gastonia, NC-SC MSA',
  'Charlottesville, VA MSA',
  'Chattanooga, TN-GA MSA',
  'Cheyenne, WY MSA',
  'Chicago-Naperville-Elgin, IL-IN-WI MSA',
  'Chico, CA MSA',
  'Cincinnati, OH-KY-IN MSA',
  'Clarksville, TN-KY MSA',
  'Cleveland-Elyria, OH MSA',
  'Cleveland, TN MSA',
  "Coeur d'Alene, ID MSA",
  'College Station-Bryan, TX MSA',
  'Colorado Springs, CO MSA',
  'Columbia, MO MSA',
  'Columbia, SC MSA',
  'Columbus, GA-AL MSA',
  'Columbus, IN MSA',
  'Columbus, OH MSA',
  'Corpus Christi, TX MSA',
  'Corvallis, OR MSA',
  'Crestview-Fort Walton Beach-Destin, FL MSA',
  'Cumberland, MD-WV MSA',
  'Dallas-Fort Worth-Arlington, TX MSA',
  'Dalton, GA MSA',
  'Danville, IL MSA',
  'Daphne-Fairhope-Foley, AL MSA',
  'Davenport-Moline-Rock Island, IA-IL MSA',
  'Dayton-Kettering, OH MSA',
  'Decatur, AL MSA',
  'Decatur, IL MSA',
  'Deltona-Daytona Beach-Ormond Beach, FL MSA',
  'Denver-Aurora-Lakewood, CO MSA',
  'Des Moines-West Des Moines, IA MSA',
  'Detroit–Warren–Dearborn, MI MSA',
  'Dothan, AL MSA',
  'Dover, DE MSA',
  'Dubuque, IA MSA',
  'Duluth, MN-WI MSA',
  'Durham-Chapel Hill, NC MSA',
  'East Stroudsburg, PA MSA',
  'Eau Claire, WI MSA',
  'El Centro, CA MSA',
  'El Paso, TX MSA',
  'Elizabethtown-Fort Knox, KY MSA',
  'Elkhart-Goshen, IN MSA',
  'Elmira, NY MSA',
  'Enid, OK MSA',
  'Erie, PA MSA',
  'Eugene-Springfield, OR MSA',
  'Evansville, IN-KY MSA',
  'Fairbanks, AK MSA',
  'Fargo, ND-MN MSA',
  'Farmington, NM MSA',
  'Fayetteville-Springdale-Rogers, AR MSA',
  'Fayetteville, NC MSA',
  'Flagstaff, AZ MSA',
  'Flint, MI MSA',
  'Florence-Muscle Shoals, AL MSA',
  'Florence, SC MSA',
  'Fond du Lac, WI MSA',
  'Fort Collins, CO MSA',
  'Fort Smith, AR-OK MSA',
  'Fort Wayne, IN MSA',
  'Fresno, CA MSA',
  'Gadsden, AL MSA',
  'Gainesville, FL MSA',
  'Gainesville, GA MSA',
  'Gettysburg, PA MSA',
  'Glens Falls, NY MSA',
  'Goldsboro, NC MSA',
  'Grand Forks, ND-MN MSA',
  'Grand Island, NE MSA',
  'Grand Junction, CO MSA',
  'Grand Rapids-Kentwood, MI MSA',
  'Grants Pass, OR MSA',
  'Great Falls, MT MSA',
  'Greeley, CO MSA',
  'Green Bay, WI MSA',
  'Greensboro-High Point, NC MSA',
  'Greenville-Anderson, SC MSA',
  'Greenville, NC MSA',
  'Gulfport-Biloxi, MS MSA',
  'Hagerstown-Martinsburg, MD-WV MSA',
  'Hammond, LA MSA',
  'Hanford-Corcoran, CA MSA',
  'Harrisburg-Carlisle, PA MSA',
  'Harrisonburg, VA MSA',
  'Hartford-East Hartford-Middletown, CT MSA',
  'Hattiesburg, MS MSA',
  'Hickory-Lenoir-Morganton, NC MSA',
  'Hilton Head Island-Bluffton-Beaufort, SC MSA',
  'Hinesville, GA MSA',
  'Homosassa Springs, FL MSA',
  'Hot Springs, AR MSA',
  'Houma-Thibodaux, LA MSA',
  'Houston-The Woodlands-Sugar Land, TX MSA',
  'Huntington-Ashland, WV-KY-OH MSA',
  'Huntsville, AL MSA',
  'Idaho Falls, ID MSA',
  'Indianapolis-Carmel-Anderson, IN MSA',
  'Iowa City, IA MSA',
  'Ithaca, NY MSA',
  'Jackson, MI MSA',
  'Jackson, MS MSA',
  'Jackson, TN MSA',
  'Jacksonville, FL MSA',
  'Jacksonville, NC MSA',
  'Janesville-Beloit, WI MSA',
  'Jefferson City, MO MSA',
  'Johnson City, TN MSA',
  'Johnstown, PA MSA',
  'Jonesboro, AR MSA',
  'Joplin, MO MSA',
  'Kahului-Wailuku-Lahaina, HI MSA',
  'Kalamazoo-Portage, MI MSA',
  'Kankakee, IL MSA',
  'Kansas City, MO-KS MSA',
  'Kennewick-Richland, WA MSA',
  'Killeen-Temple, TX MSA',
  'Kingsport-Bristol, TN-VA MSA',
  'Kingston, NY MSA',
  'Knoxville, TN MSA',
  'Kokomo, IN MSA',
  'La Crosse-Onalaska, WI-MN MSA',
  'Lafayette-West Lafayette, IN MSA',
  'Lafayette, LA MSA',
  'Lake Charles, LA MSA',
  'Lake Havasu City-Kingman, AZ MSA',
  'Lakeland-Winter Haven, FL MSA',
  'Lancaster, PA MSA',
  'Lansing-East Lansing, MI MSA',
  'Laredo, TX MSA',
  'Las Cruces, NM MSA',
  'Las Vegas-Henderson-Paradise, NV MSA',
  'Lawrence, KS MSA',
  'Lawton, OK MSA',
  'Lebanon, PA MSA',
  'Lewiston-Auburn, ME MSA',
  'Lewiston, ID-WA MSA',
  'Lexington-Fayette, KY MSA',
  'Lima, OH MSA',
  'Lincoln, NE MSA',
  'Little Rock-North Little Rock-Conway, AR MSA',
  'Logan, UT-ID MSA',
  'Longview, TX MSA',
  'Longview, WA MSA',
  'Los Angeles-Long Beach-Anaheim, CA MSA',
  'Louisville/Jefferson County, KY-IN MSA',
  'Lubbock, TX MSA',
  'Lynchburg, VA MSA',
  'Macon-Bibb County, GA MSA',
  'Madera, CA MSA',
  'Madison, WI MSA',
  'Manchester-Nashua, NH MSA',
  'Manhattan, KS MSA',
  'Mankato, MN MSA',
  'Mansfield, OH MSA',
  'McAllen-Edinburg-Mission, TX MSA',
  'Medford, OR MSA',
  'Memphis, TN-MS-AR MSA',
  'Merced, CA MSA',
  'Miami-Fort Lauderdale-West Palm Beach, FL MSA',
  'Michigan City-La Porte, IN MSA',
  'Midland, MI MSA',
  'Midland, TX MSA',
  'Milwaukee-Waukesha, WI MSA',
  'Minneapolis-St. Paul-Bloomington, MN-WI MSA',
  'Missoula, MT MSA',
  'Mobile, AL MSA',
  'Modesto, CA MSA',
  'Monroe, LA MSA',
  'Monroe, MI MSA',
  'Montgomery, AL MSA',
  'Morgantown, WV MSA',
  'Morristown, TN MSA',
  'Mount Vernon-Anacortes, WA MSA',
  'Muncie, IN MSA',
  'Muskegon, MI MSA',
  'Myrtle Beach-Conway-North Myrtle Beach, SC-NC MSA',
  'Napa, CA MSA',
  'Naples-Marco Island, FL MSA',
  'Nashville-Davidson–Murfreesboro–Franklin, TN MSA',
  'New Bern, NC MSA',
  'New Haven-Milford, CT MSA',
  'New Orleans-Metairie, LA MSA',
  'New York-Newark-Jersey City, NY-NJ-PA MSA',
  'Niles, MI MSA',
  'North Port-Sarasota-Bradenton, FL MSA',
  'Norwich-New London, CT MSA',
  'Ocala, FL MSA',
  'Ocean City, NJ MSA',
  'Odessa, TX MSA',
  'Ogden-Clearfield, UT MSA',
  'Oklahoma City, OK MSA',
  'Olympia-Lacey-Tumwater, WA MSA',
  'Omaha-Council Bluffs, NE-IA MSA',
  'Orlando-Kissimmee-Sanford, FL MSA',
  'Oshkosh-Neenah, WI MSA',
  'Owensboro, KY MSA',
  'Oxnard-Thousand Oaks-Ventura, CA MSA',
  'Palm Bay-Melbourne-Titusville, FL MSA',
  'Panama City, FL MSA',
  'Parkersburg-Vienna, WV MSA',
  'Pensacola-Ferry Pass-Brent, FL MSA',
  'Peoria, IL MSA',
  'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA',
  'Phoenix-Mesa-Chandler, AZ MSA',
  'Pine Bluff, AR MSA',
  'Pittsburgh, PA MSA',
  'Pittsfield, MA MSA',
  'Pocatello, ID MSA',
  'Port St. Lucie, FL MSA',
  'Portland-South Portland, ME MSA',
  'Portland-Vancouver-Hillsboro, OR-WA MSA',
  'Poughkeepsie-Newburgh-Middletown, NY MSA',
  'Prescott Valley-Prescott, AZ MSA',
  'Providence-Warwick, RI-MA MSA',
  'Provo-Orem, UT MSA',
  'Pueblo, CO MSA',
  'Punta Gorda, FL MSA',
  'Racine, WI MSA',
  'Raleigh-Cary, NC MSA',
  'Rapid City, SD MSA',
  'Reading, PA MSA',
  'Redding, CA MSA',
  'Reno, NV MSA',
  'Richmond, VA MSA',
  'Riverside-San Bernardino-Ontario, CA MSA',
  'Roanoke, VA MSA',
  'Rochester, MN MSA',
  'Rochester, NY MSA',
  'Rockford, IL MSA',
  'Rocky Mount, NC MSA',
  'Rome, GA MSA',
  'Sacramento-Roseville-Folsom, CA MSA',
  'Saginaw, MI MSA',
  'Salem, OR MSA',
  'Salinas, CA MSA',
  'Salisbury, MD-DE MSA',
  'Salt Lake City, UT MSA',
  'San Angelo, TX MSA',
  'San Antonio-New Braunfels, TX MSA',
  'San Diego-Chula Vista-Carlsbad, CA MSA',
  'San Francisco-Oakland-Berkeley, CA MSA',
  'San Jose-Sunnyvale-Santa Clara, CA MSA',
  'San Luis Obispo-Paso Robles, CA MSA',
  'Santa Cruz-Watsonville, CA MSA',
  'Santa Fe, NM MSA',
  'Santa Maria-Santa Barbara, CA MSA',
  'Santa Rosa-Petaluma, CA MSA',
  'Savannah, GA MSA',
  'Scranton–Wilkes-Barre, PA MSA',
  'Seattle-Tacoma-Bellevue, WA MSA',
  'Sebastian-Vero Beach, FL MSA',
  'Sebring-Avon Park, FL MSA',
  'Sheboygan, WI MSA',
  'Sherman-Denison, TX MSA',
  'Shreveport-Bossier City, LA MSA',
  'Sierra Vista-Douglas, AZ MSA',
  'Sioux City, IA-NE-SD MSA',
  'Sioux Falls, SD MSA',
  'South Bend-Mishawaka, IN-MI MSA',
  'Spartanburg, SC MSA',
  'Spokane-Spokane Valley, WA MSA',
  'Springfield, IL MSA',
  'Springfield, MA MSA',
  'Springfield, MO MSA',
  'Springfield, OH MSA',
  'St. Cloud, MN MSA',
  'St. George, UT MSA',
  'St. Joseph, MO-KS MSA',
  'St. Louis, MO-IL MSA',
  'State College, PA MSA',
  'Staunton, VA MSA',
  'Stockton, CA MSA',
  'Sumter, SC MSA',
  'Syracuse, NY MSA',
  'Tallahassee, FL MSA',
  'Tampa-St. Petersburg-Clearwater, FL MSA',
  'Terre Haute, IN MSA',
  'Texarkana, TX-AR MSA',
  'The Villages, FL MSA',
  'Toledo, OH MSA',
  'Topeka, KS MSA',
  'Trenton-Princeton, NJ MSA',
  'Tucson, AZ MSA',
  'Tulsa, OK MSA',
  'Tuscaloosa, AL MSA',
  'Twin Falls, ID MSA',
  'Tyler, TX MSA',
  'Urban Honolulu, HI MSA',
  'Utica-Rome, NY MSA',
  'Valdosta, GA MSA',
  'Vallejo, CA MSA',
  'Victoria, TX MSA',
  'Vineland-Bridgeton, NJ MSA',
  'Virginia Beach-Norfolk-Newport News, VA-NC MSA',
  'Visalia, CA MSA',
  'Waco, TX MSA',
  'Walla Walla, WA MSA',
  'Warner Robins, GA MSA',
  'Washington-Arlington-Alexandria, DC-VA-MD-WV MSA',
  'Waterloo-Cedar Falls, IA MSA',
  'Watertown-Fort Drum, NY MSA',
  'Wausau-Weston, WI MSA',
  'Weirton-Steubenville, WV-OH MSA',
  'Wenatchee, WA MSA',
  'Wheeling, WV-OH MSA',
  'Wichita Falls, TX MSA',
  'Wichita, KS MSA',
  'Williamsport, PA MSA',
  'Wilmington, NC MSA',
  'Winchester, VA-WV MSA',
  'Winston-Salem, NC MSA',
  'Worcester, MA-CT MSA',
  'Yakima, WA MSA',
  'York-Hanover, PA MSA',
  'Youngstown-Warren-Boardman, OH-PA MSA',
  'Yuba City, CA MSA',
  'Yuma, AZ MSA'
]

let select_elem = document.getElementById('Warehouse-Location---Metro-Area')

areaList.forEach((element) => {
  let option_elem = document.createElement('option')

  // Add index to option_elem
  option_elem.value = element

  // Add element HTML
  option_elem.textContent = element

  // Append option_elem to select_elem
  select_elem.appendChild(option_elem)
})
